connectionStrings:
  DefaultConnection: "Data Source=identity.db"

# providers:
#   google:
#     ClientId: "..."
#     ClientSecret: "..."
#   facebook:
#     ClientId: "..."
#     ClientSecret: "..."
#   microsoft:
#     ClientId: "..."
#     ClientSecret: "..."
#   github:
#     ClientId: "..."
#     ClientSecret: "..."
